# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peticion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
