# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peticion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='usuario',
            field=models.ForeignKey(default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
