# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peticion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='person',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='petici',
        ),
    ]
