# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peticion', '0002_auto_20180605_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peticion',
            name='usuario',
        ),
    ]
