# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesia',
            name='direccion',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='imagen',
            field=models.ImageField(default=b'', upload_to=b'imagenes_iglesia'),
        ),
    ]
