# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_auto_20180603_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
