# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-03 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='iglesia',
            new_name='iglesiaa',
        ),
    ]
