# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-03 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180603_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='iglesiaa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia'),
        ),
    ]
